#
# This source file is part of the VISTA-Stanford projects
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see AUTHORS.md)
#
# SPDX-License-Identifier: MIT
#

name: "\U0001F41E BUG"

description: Submit a bug report for this project
title: "Bug report: Provide a descriptive title here."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug you encountered in detail.
      placeholder: Clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Outline the steps required to reproduce the bug.
      placeholder: Step-by-step instructions to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expectedbehavior
    attributes:
      label: Expected Outcome
      description: What did you expect to happen instead of the bug?
      placeholder: Clear description of the expected behavior.
    validations:
      required: true

  - type: textarea
    id: additionalcontext
    attributes:
      label: Additional Information
      description: Include any other context or details relevant to this bug report.
      placeholder: Any extra information that may help in diagnosing the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Code Guidelines
      description: By submitting this issue, you confirm that you will adhere to the [Coding Guidelines](https://github.com/DaneshjouLab/.github/blob/main/CODING_GUIDELINES.md)
      options:
        - label: I agree to follow the Coding Guidelines for this project
          required: true
